### ISSUE TITLE
Gitlab CI/CD 初探

### ISSUE THREAD

**Issue by yangkean** [yangkean/blog#10]
# Gitlab CI/CD 初探

> 探索 gitlab CI/CD 的一篇小文，包含了 gitlab 的安装和 CI/CD 的研究。

## gitlab 安装及配置

官网有很多种安装方式，方便起见，不想做过多配置，直接走 [Docker 安装](https://docs.gitlab.com/ee/install/docker.html)。

Mac 如果是较新的系统可以直接按 [文档](https://docs.docker.com/docker-for-mac/install/) 来。旧系统只能找对应支持的 [旧版本 Docker](https://docs.docker.com/docker-for-mac/previous-versions/)，新版本不兼容。

装好 Docker 后，需要装 gitlab 的 [社区版本](https://hub.docker.com/r/gitlab/gitlab-ce)，商业版本毕竟要钱。命令行输入：

```bash
$ docker pull gitlab/gitlab-ce
```

参照 [文档](https://docs.gitlab.com/ee/install/docker.html) 配置 gitlab，下面均默认 Mac 系统。

命令行执行：

```bash
$ export GITLAB_HOME=$HOME/gitlab
```

用于 gitlab 容器中相关数据的存储。

执行：

```bash
sudo docker run --detach \
  --hostname gitlab.yangkean.com \
  --publish 443:443 --publish 8000:8000 --publish 2222:22 \
  --name gitlab \
  --restart always \
  --volume $GITLAB_HOME/config:/etc/gitlab \
  --volume $GITLAB_HOME/logs:/var/log/gitlab \
  --volume $GITLAB_HOME/data:/var/opt/gitlab \
  gitlab/gitlab-ce
```

部分说明：

`--detach` 在后台中运行容器

`--hostname` 设置容器主机名

`--publish 2222:22` 把容器的端口22映射到外部2222端口，其他类似。需要注意的是 http(s) 绑定新端口时需要 [端口一致](https://gitlab.com/gitlab-org/omnibus-gitlab/-/merge_requests/1365)。

`—name gitlab`  容器的名称, 可用于命令中，如重启容器：docker restart gitlab

`--restart always` 自动重启

`—volume` 将容器的路径映射到容器外部

几个常用命令：

```bash
$ docker ps # 列举所有容器，可以查看容器 ID
$ docker restart [container name] # 重启相应的容器
$ docker kill [container id] # 干掉当前在跑的某个容器
$ docker image ls # 列举所有已安装镜像
$ docker stats # 容器运行时的资源使用情况
```

接下来是需要修改配置文件，找到 `$GITLAB_HOME/config/gitlab.rb`，找到并修改如下几行：

```ruby
# 访问 gitlab 的地址，端口默认为 80
external_url 'http://127.0.0.1:8000'

# 设置 ssh 服务的访问地址
gitlab_rails['gitlab_ssh_host'] = '127.0.0.1'

# 设置 ssh 服务访问的端口
gitlab_rails['gitlab_shell_ssh_port'] = 2222

# nginx 端口设置
nginx['listen_port'] = 8000
```

访问 127.0.0.1（或者自行在 hosts 文件里配置域名的映射）即可看到 gitlab。管理员账号是 `root`，密码在 `$GITLAB_HOME/config/initial_root_password` 文件里，登录后自行修改。或可直接 [设置初始密码](https://docs.gitlab.com/omnibus/installation/#set-up-the-initial-password)。

## CI/CD

Gitlab CI/CD 是 gitlab 内置的用于持续集成和持续部署的工具，每次推送代码到仓库中都会根据根目录下的 `.gitlab-ci.yml` 文件执行一系列脚本，完成构建、测试、验证、发布等任务。我们可以使用 gitlab 提供的 shared runner 来执行  `.gitlab-ci.yml` 中的任务，也可以使用 gitlab 提供的 `gitlab-runner` 程序在我们选择的机器上执行。我这里使用 `gitlab-runner` 的方式。

### 安装 gitlab runner

方式也很多，这里使用 [Docker 方式安装 gitlab runner](https://docs.gitlab.com/runner/install/docker.html#option-2-use-docker-volumes-to-start-the-runner-container)。

```bash
$ docker volume create gitlab-runner-config
```

```bash
$ docker run -d --name gitlab-runner --restart always \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v gitlab-runner-config:/etc/gitlab-runner \
    gitlab/gitlab-runner:latest
```

注册 runner：

```bash
$ docker run --rm -it -v gitlab-runner-config:/etc/gitlab-runner gitlab/gitlab-runner:latest register
```

按照提示输入，URL 和 token 可以在项目的设置中的 CI/CD 页查看到。需要注意的是，URL 建议使用 外网 IP 或 内网 IP，而不是 localhost 之类的 IP，会有问题。

## 编写 .gitlab-ci.yml 

一个简单的 gitlab-ci 配置文件是这样的：

```yaml
stages: # 分阶段
    - install
    - eslint
    - build
    - deploy

cache: # 缓存，为了避免在执行新 stage 时以下的文件夹被清空无法找到
    paths:
        - node_modules
        - build

install-job:
    tags: # 这里的 tag 是我们在 runner 中定义的 tag，只有有 tag 才会被相应的 runner 执行
        - demo
    stage: install # 所属的 stage
    script: # 当前 job 执行的脚本，可以有多段脚本
        - npm install

eslint-job:
    tags:
        - demo
    stage: eslint
    script:
        - npm run lint

build-job:
    tags:
        - demo
    stage: build
    script:
        - npm run build

deploy-job:
    tags:
        - demo
    stage: deploy
    script:
        - echo "start to deploy"

```

这个文件放在项目根目录中，gitlab runner 会根据这个这个文件来执行 pipeline，也就是管道流程，它包含多个 stage，每个 stage 代表一个阶段，可以理解为是我们在软件开发中的一些阶段，安装、lint、构建、部署等，每个 stage 都可以包含多个 job，每个 job 完成所属 stage 的一些任务，所有的 job 完成之后，整个 pipeline 就完成啦。

现在可以提交代码到仓库中看看效果啦！

## Reference

* [使用GitLab实现CI/CD](https://zhuanlan.zhihu.com/p/136843588)
* [Gitlab-ci:从零开始的前端自动化部署](https://zhuanlan.zhihu.com/p/184936276)
* [Your Private CI/CD using self-hosted GitLab and Docker](https://oramind.com/private-cicd-using-gitlab-docker/)
* [官网 .gitlab-ci.yml 模板](https://gitlab.com/gitlab-com/www-gitlab-com/-/blob/master/.gitlab-ci.yml)
